// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNlR1UkkZ9SwiKyR9unYKLAMbmd_LG_1k',
    appId: '1:279350055759:web:8e5a5dc9a7a94f0bc46b3a',
    messagingSenderId: '279350055759',
    projectId: 'radio90fm-3cc99',
    authDomain: 'radio90fm-3cc99.firebaseapp.com',
    storageBucket: 'radio90fm-3cc99.appspot.com',
    measurementId: 'G-8GDKD573V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBppiKZuIImtQF_L6uPPSRIXmVLME7WHBQ',
    appId: '1:279350055759:android:43715fa5fd544986c46b3a',
    messagingSenderId: '279350055759',
    projectId: 'radio90fm-3cc99',
    storageBucket: 'radio90fm-3cc99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHfXVnUXIqafSEwslz8c1IxbRCixqG0ZM',
    appId: '1:279350055759:ios:e0369f4cf219bcf9c46b3a',
    messagingSenderId: '279350055759',
    projectId: 'radio90fm-3cc99',
    storageBucket: 'radio90fm-3cc99.appspot.com',
    iosBundleId: 'com.radio90fm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHfXVnUXIqafSEwslz8c1IxbRCixqG0ZM',
    appId: '1:279350055759:ios:fa675ff6971d5a71c46b3a',
    messagingSenderId: '279350055759',
    projectId: 'radio90fm-3cc99',
    storageBucket: 'radio90fm-3cc99.appspot.com',
    iosBundleId: 'com.example.radio90fm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNlR1UkkZ9SwiKyR9unYKLAMbmd_LG_1k',
    appId: '1:279350055759:web:923ade51ab299fa2c46b3a',
    messagingSenderId: '279350055759',
    projectId: 'radio90fm-3cc99',
    authDomain: 'radio90fm-3cc99.firebaseapp.com',
    storageBucket: 'radio90fm-3cc99.appspot.com',
    measurementId: 'G-PZ3C7ZMRE8',
  );

}